---
- name: Update package
  command: apt update
  become: yes
  when: operation == "apply"
 
- name: Install Java{{ version }}
  apt:
    name: openjdk-{{ version }}-jdk
    state: present
  become: yes
  when: operation == "apply"
 
- name: Uninstall Java{{ version }}
  apt:
    name: openjdk-{{ version }}-jdk
    state: absent
  become: yes
  when: operation == "destroy"
