---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: 
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libdb5.3-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - tk-dev
      - libffi-dev
      - wget
    state: present

- name: Download Python
  get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "/tmp/Python-{{ python_version }}.tgz"

- name: Extract Python
  unarchive:
    src: "/tmp/Python-{{ python_version }}.tgz"
    dest: "/tmp"
    remote_src: yes

- name: Install Python
  shell: |
    cd /tmp/Python-{{ python_version }}
    ./configure --enable-optimizations
    make altinstall

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Ensure pip is installed
  command: "python{{ python_version | regex_replace('\\.\\d+$') }} /tmp/get-pip.py"

- name: Verify Python installation
  command: "python{{ python_version | regex_replace('\\.\\d+$') }} --version"
  register: python_version_output

- debug:
    msg: "Installed Python version is {{ python_version_output.stdout }}"

